/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.GameScene {
	import laya.ui.*;
	import laya.display.*;
	import script.GameStart;
	import script.Controller;
	import laya.physics.RigidBody;
	import laya.physics.ChainCollider;
	import laya.physics.CircleCollider;

	public class GameMainSceneUI extends Scene {

		override protected function createChildren():void {
			super.createChildren();
			loadScene("GameScene/GameMainScene");

		}

	}
}