/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package {
	import laya.utils.ClassUtils;
	import laya.ui.View;
	import laya.webgl.WebGL;
	import script.GameStart;
	import script.Controller;
	import laya.physics.RigidBody;
	import laya.physics.ChainCollider;
	import laya.physics.CircleCollider;
	import laya.physics.BoxCollider;
	import enemyScript.BossTopOne;
	import enemyScript.BossTopTow;
	import enemyScript.BossFoot;
	import enemyScript.BossOne;
	import enemyScript.BossOneBullet;
	import script.Bullet;
	import enemyScript.EnemyBullet;
	import enemyScript.EnemyFive;
	import enemyScript.EnemyFour;
	import enemyScript.EnemyOne;
	import enemyScript.EnemyThree;
	import enemyScript.EnemyTow;
	import propScript.FlyProp;
	import propScript.PropB;
	import propScript.PropF;
	import propScript.PropFrame;
	import propScript.PropL;
	import propScript.PropM;
	import propScript.PropR;
	import propScript.PropS;
	import script.Role;
	import propScript.TouchDestroy;
	/**
	 * 游戏初始化配置
	 */
	public class GameConfig {
		public static var width:int = 640;
		public static var height:int = 1136;
		public static var scaleMode:String = "fixedwidth";
		public static var screenMode:String = "none";
		public static var alignV:String = "top";
		public static var alignH:String = "left";
		public static var startScene:* = "GameScene/GameMainScene.scene";
		public static var sceneRoot:String = "";
		public static var debug:Boolean = false;
		public static var stat:Boolean = false;
		public static var physicsDebug:Boolean = false;
		public static var exportSceneToJson:Boolean = true;
		
		public static function init():void {
			//注册Script或者Runtime引用
			var reg:Function = ClassUtils.regClass;
			reg("script.GameStart",GameStart);
			reg("script.Controller",Controller);
			reg("laya.physics.RigidBody",RigidBody);
			reg("laya.physics.ChainCollider",ChainCollider);
			reg("laya.physics.CircleCollider",CircleCollider);
			reg("laya.physics.BoxCollider",BoxCollider);
			reg("enemyScript.BossTopOne",BossTopOne);
			reg("enemyScript.BossTopTow",BossTopTow);
			reg("enemyScript.BossFoot",BossFoot);
			reg("enemyScript.BossOne",BossOne);
			reg("enemyScript.BossOneBullet",BossOneBullet);
			reg("script.Bullet",Bullet);
			reg("enemyScript.EnemyBullet",EnemyBullet);
			reg("enemyScript.EnemyFive",EnemyFive);
			reg("enemyScript.EnemyFour",EnemyFour);
			reg("enemyScript.EnemyOne",EnemyOne);
			reg("enemyScript.EnemyThree",EnemyThree);
			reg("enemyScript.EnemyTow",EnemyTow);
			reg("propScript.FlyProp",FlyProp);
			reg("propScript.PropB",PropB);
			reg("propScript.PropF",PropF);
			reg("propScript.PropFrame",PropFrame);
			reg("propScript.PropL",PropL);
			reg("propScript.PropM",PropM);
			reg("propScript.PropR",PropR);
			reg("propScript.PropS",PropS);
			reg("script.Role",Role);
			reg("propScript.TouchDestroy",TouchDestroy);
		}
		GameConfig.init();
	}
}