/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package {
	import laya.utils.ClassUtils;
	import laya.ui.View;
	import laya.webgl.WebGL;
	import script.GameStart;
	import script.Controller;
	import laya.physics.BoxCollider;
	import laya.physics.RigidBody;
	import script.Role;
	/**
	 * 游戏初始化配置
	 */
	public class GameConfig {
		public static var width:int = 640;
		public static var height:int = 1136;
		public static var scaleMode:String = "fixedwidth";
		public static var screenMode:String = "none";
		public static var alignV:String = "top";
		public static var alignH:String = "left";
		public static var startScene:* = "GameScene/GameMainScene.scene";
		public static var sceneRoot:String = "";
		public static var debug:Boolean = false;
		public static var stat:Boolean = false;
		public static var physicsDebug:Boolean = false;
		public static var exportSceneToJson:Boolean = true;
		
		public static function init():void {
			//注册Script或者Runtime引用
			var reg:Function = ClassUtils.regClass;
			reg("script.GameStart",GameStart);
			reg("script.Controller",Controller);
			reg("laya.physics.BoxCollider",BoxCollider);
			reg("laya.physics.RigidBody",RigidBody);
			reg("script.Role",Role);
		}
		GameConfig.init();
	}
}